[package]
name = "temp"
version = "1.0.0"
authors = [
    "123",
]
license = "Apache-2.0"
edition = "2018"
description = "123"

[[bin]]
name = "temp"

[lib]
doctest = false

[dependencies]
compiler-common = { git = "git@github.com:warsmit-projects/test_ci.git" }
