name: tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # let's make sure our tests pass on Chrome browser
    name: Smoke testing
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run test
        run: node test.js
      # - name: Cypress run
      #   uses: cypress-io/github-action@v2
      #   with:
      #     browser: chrome
      #     record: true
      #     group: Tests on Chrome
      #   env:
      #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      #     CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}