name: tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # let's make sure our tests pass on Chrome browser
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome



name: example-config
on: [push]
jobs:
  start:
    # example where we pass custom base URL
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/config
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3333'
          config: baseUrl=http://localhost:3333

  separate-specs:
    # example where we pass specs to run via multiple lines
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/config
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3333'
          config: baseUrl=http://localhost:3000
          spec: |
            cypress/integration/spec-a.js
            cypress/integration/spec-b.js
  separate-specs-with-wildcard:
    # example where we pass specs to run via multiple lines and wildcards
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: ./
        with:
          working-directory: examples/config
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3333'
          config: baseUrl=http://localhost:3333
          spec: |
            cypress/integration/spec-a.js
            cypress/**/*-b.js