name: tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # let's make sure our tests pass on Chrome browser
    name: Smoke testing
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: yarn
        run: yarn
      - name: Install Dependencies
        uses: actions/setup-node@v1
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        with:
          args: install
      - name: Test Code
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: yarn test -- ./tests/test_pup.test.js
